# PR's only

name: Validate

on:
  pull_request:
    branches: [main]

permissions: read-all

env:
  FORCE_COLOR: 1

jobs:
  _:
    uses: medikoo/github-actions-workflows/.github/workflows/0.12-validate.yml@main
